title: dingers
description: for the music

google_analytics: UA-89975046-2

show_excerpts: true

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

collections:
  posts:
    output: true
    permalink: /:title
